### ISSUE TITLE
Never use DBUpdate/Insert on language

### ISSUE THREAD

**Issue by potehinre** [GenesisKernel/apps#4]
https://github.com/GenesisKernel/apps/blob/fb9961e3b57ecff47c9db2eb1cb9e3a27c3c463d/src/admin/contracts/EditLang.sim#L12
You should use UpdateLang, because of VM internals

**Comment by CynepHy6** [comment]
fixed
NewLang: CreateLanguage($Name, $Trans, $ApplicationId)
EditLang: EditLanguage($Id, $lang["name"], $Trans, Int($lang["app_id"]))
