### ISSUE TITLE
Language ext: ability to serialize map to json

### ISSUE THREAD

**Issue by potehinre** [GenesisKernel/apps#6]
https://github.com/GenesisKernel/apps/blob/fb9961e3b57ecff47c9db2eb1cb9e3a27c3c463d/src/admin/contracts/EditTable.sim#L10
It's a very bad way serialize record to JSON.
```
$Permissions = Sprintf(`{"insert":%q,"update":%q,"new_column":%q}`, $Insert_con, $Update_con, $New_column_con)```
better way is first to make a map, then serialize it to JSON:

```
var permissions map
permissions["insert"] = $Insert_con
permissions["update"] = $Update_con
permissions["new_column"] = $New_column_con
$Permissions = MapToJson(permissions)

```

**Comment by syypoo** [comment]
done
