### ISSUE TITLE
Incorrect Add function names

### ISSUE THREAD

**Issue by potehinre** [GenesisKernel/apps#9]
https://github.com/GenesisKernel/apps/blob/fb9961e3b57ecff47c9db2eb1cb9e3a27c3c463d/src/admin/contracts/Export.sim#L61
AddPage, AddTable,... is not actually adds something, instead it returns serialized entity,
so better names is PageJSON, TableJSON, it's also better to use MapToJSON(), instead of Sprintf'ing.

**Comment by syypoo** [comment]
done
